workflows:
  ios-app-store:
    name: StatsAnaliz App Store Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Apple Key"
    environment:
      xcode: latest
    scripts:
      - name: Sertifika ve Profili Mac'e Kur
        script: |
          keychain initialize
          keychain add-certificates --certificate "ios_distribution.p12" --certificate-password "123456"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "StatsAnaliz.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: iOS Uygulamasını Derle (Archive)
        script: xcode-project build-ipa --project "statsAnaliz.xcodeproj" --scheme "statsAnaliz"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true